version: '3'

services:
  viz:
    image: dockersamples/visualizer:latest
    ports:
      - 8090:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints:
          - node.role == manager
  ais-data-fetcher-1:
    image: kenguru33/ais-data-fetcher:latest
    environment:
      - URL=http://ais.rs.no/aktive_pos.json
    depends_on:
      - message-bus
    networks:
      - aisnet
  ais-data-fetcher-2:
      image: kenguru33/ais-data-fetcher:latest
      environment:
        - URL=http://ais.rs.no/aktive_pos.json
      depends_on:
        - message-bus
      networks:
        - aisnet
  message-bus:
    image: rabbitmq:3-management
    ports:
      - 8080:15672
    networks:
      - aisnet
networks:
  aisnet:
    driver: overlay
